defaultTheme = "auto"
gitRepo = "https://github.com/raikan-san/raikan-san.github.io"
fingerprint = ""
enablePWA = true
dateFormat = "2006-01-02"
title = "glitched echoes"
description = ""
images = []
bundle = true

[author]
name = "raikan-san"
email = "raikan-san@proton.me"
link = "https://raikan-san.is-a.dev"

[header.title]
logo = ""
name = "glitched echoes"
pre = ""
post = ""
typeit = true

[home.profile]
enable = true
gravatarEmail = "raikan-san@proton.me"
avatarURL = ""
title = "Salutations, Wanderer."
subtitle = "I am raikan, a voyager of the digital wastelands on a journey to piece together the remnants of broken data and explore the buried truths hidden in the chaos. These are my transmissions for those listening."
typeit = true
social = true
disclaimer = "Proceed with caution—what you find may be as fragmented as the world you’ve left behind."

[search]
enable = true
# type of search engine ("algolia", "fuse")
type = "fuse"
# max index length of the chunked content
contentLength = 4000
# placeholder of the search bar
placeholder = ""
# DoIt NEW | 0.2.1 max number of results length
maxResultLength = 10
# DoIt NEW | 0.2.3 snippet length of the result
snippetLength = 30
# DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
highlightTag = "em"
# DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
absoluteURL = false

[search.fuse]
# DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[social]
GitHub = "raikan-san"
Linkedin = "vineet-pratik-agarwal"
Stackoverflow = ""
Steam = ""
Mastodon = "@raikan_san"
Ko-Fi = "raikan-san"
Email = "raikan-san@proton.me"
RSS = true # DoIt NEW | 0.2.0

[footer]
enable = true
custom = ""
hostedOn = '<a title="is-a.dev" href="https://www.is-a.dev/" target="_blank" rel="noopener noreffer">is-a.dev</a>'
hugo = false
copyright = true
author = true
#since = 2022
icp = ""
license = '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/licenses/GPL-3.0" target="_blank">GPL-3.0</a>'
